mode: deploy
# rancheros_version: v0.7.1
# rancheros_iso_url: https://releases.rancher.com/os/{{rancheros_version}}/rancheros.iso
# rancher_version: v1.2.0
# rancher_image: rancher/server:{{ rancher_version }}

version:
  rancher:
    os: v0.7.1
    agent: v1.1.0
    server: v1.2.0

rancher:
  server:
    image: rancher/server:{{ version.rancher.server }}
    port:
      http: 8080

  os:
    version: v0.7.1
    iso: https://releases.rancher.com/os/{{ version.rancher.os }}/rancheros.iso

  agent:
    version: v0.7.10
    image: rancher/agent:{{ version.rancher.agent }}


docker:
  recreate: false
  restart:
    policy: unless-stopped